baseURL = "/"
languageCode = "en-us"
title = "Wenping Zou"
description = "Ph.D Student, University of Houston"
theme = "min_night"
disqusShortname = ""
googleAnalytics = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "public/"]

[permalinks]
    post = "/:year/:month/:day/:slug/"

[params]
    author = "Wenping Zou"
    description = "Ph.D Student, University of Houston"
    logo = "wenpingzou2018.jpg"
    twitterAuthor = "@WenpingZou"
    githubUsername = "zouwenping1991"
    accent = "#386890" # dark colors do best
    backgroundColor = "#f5f5f5"
    font = "Mina" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "lakeside-light" # make this match accent
    highlightLanguages = ["r", "bash", "go"]

# adjust these as you see fit
[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/About/"
    name = "About"
    weight = 2
    
[[menu.main]]
    url = "/Research/"
    name = "Research"
    weight = 3

[[menu.main]]
    url = "/Publications/"
    name = "Publications"
    weight = 4
    
#[[menu.main]]
   # url = "/Education/"
    #name = "Education"
    #weight = 5
[[menu.main]]
    url = "/Teaching/"
    name = "Teaching"
    weight = 5
# Social icons to be shown on the right-hand side of the navigation bar
# The "name" field should match the name of the icon to be used
# The list of available icons can be found at http://fontawesome.io/icons/

[[menu.icon]]
    url = "mailto:nathancday@gmail.com"
    name = "far fa-envelope"
    weight = 1

[[menu.icon]]
    url = "https://github.com/NathanCDay"
    name = "fab fa-github"
    weight = 2

[[menu.icon]]
    url = "https://twitter.com/natedayta/"
    name = "fab fa-twitter"
    weight = 3

[[menu.icon]]
    url = "https://www.linkedin.com/in/nathan-day-59b48435/"
    name = "fab fa-linkedin"
    weight = 4

[[menu.icon]]
    url = "https://www.stackoverflow.com/users/5878751/nate"
    name = "fab fa-stack-overflow"
    weight = 5
